let class_ = 6;
let car = 'subaru';
let isPassed = true;
let myphone = 'Motorola';
let day = "Sunday";
let bag = 'available';
let laptop = 'Dell';
let fan = 'yes';
let food = 'biryani';
let city = 'karachi';
console.log("Is class >= 6? I predict True. ", class_ >= 6);
console.log("Is car == 'suzuki'? I predict True. ", car == 'suzuki');
console.log('Is true == false ', isPassed == true);
console.log('Is bag available? ', bag === 'available');
console.log('Do you have Dell laptop?', laptop === 'Dell');
console.log('Do you like pizza?', food === 'pizza');
console.log('Do you live in hyderabad?', city === 'hyderabad');
console.log('Are you the fan of Babar Azam?', fan === 'yes');
console.log('Is my phone Samsung? ', myphone == 'Samsung');
console.log('Is today Monday? ', day == 'Monday');
export {};
